# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/covalent_api',
                'doc_host': 'https://hamish-haggerty.github.io',
                'git_url': 'https://github.com/hamish-haggerty/covalent_api',
                'lib_path': 'covalent_api'},
  'syms': {'covalent_api.core': {'covalent_api.core.foo': ('core.html#foo', 'covalent_api/core.py')}}}
